version: "3"
services:
  travel-plan-elasticsearch:
    build: microservicecloud-provider-dept-hystrix-8002
    image: travel-plan-elasticsearch
    container_name: travel-plan-elasticsearch.local
    ports:
      - "8002:8002"
    volumes:
      - ./log:/log

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
  #
  #  kibana:
  #    image: docker.elastic.co/kibana/kibana:7.9.0
  #    container_name: kibana
  #    hostname: kibana
  #    environment:
  #      ES_JAVA_OPTS: "-Xms1g -Xmx2g"
  #    ports:
  #      - "5601:5601"
  #    links:
  #      - elasticsearch
  #    depends_on:
  #      - elasticsearch
  #    volumes:
  #      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  #      - ./bundle-ssl/kibana/kibana.crt:/usr/share/kibana/config/kibana.crt
  #      - ./bundle-ssl/kibana/kibana.key:/usr/share/kibana/config/kibana.key
  #      - ./bundle-ssl/ca/ca.crt:/usr/share/kibana/config/ca.crt
  #
  #  logstash:
  #    image: docker.elastic.co/logstash/logstash:7.9.0
  #    container_name: logstash
  #    hostname: logstash
  #    command: logstash -f /etc/logstash/conf.d/logstash.conf
  #    volumes:
  #      - ../conf.d:/etc/logstash/conf.d
  #      - ./bundle-ssl/ca/ca.crt:/etc/logstash/config/ca.crt
  #      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
  #    links:
  #      - elasticsearch
  #    depends_on:
  #      - elasticsearch
  #    ports:
  #      - "4560:4560"
  #      - "9600:9600"
  #      - "5044:5044"
  #

networks:
  default:
    external:
      name: test-dev-shared-network